// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAps2sPcA7_Qvv5Z_l_KOWTuy79C8uiBiE',
    appId: '1:601431274476:web:bb40038a1da101973406c9',
    messagingSenderId: '601431274476',
    projectId: 'engoapp-91373',
    authDomain: 'engoapp-91373.firebaseapp.com',
    storageBucket: 'engoapp-91373.firebasestorage.app',
    measurementId: 'G-1GY5KNCH84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNTqBKPYvsCWlDFqqHlWfwpPSH3JdNHpg',
    appId: '1:601431274476:android:a74936f9bca809353406c9',
    messagingSenderId: '601431274476',
    projectId: 'engoapp-91373',
    storageBucket: 'engoapp-91373.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfqGSko9gfFalkxltbzVipg7AXf3grs2c',
    appId: '1:601431274476:ios:9b792cb3b8cc9d883406c9',
    messagingSenderId: '601431274476',
    projectId: 'engoapp-91373',
    storageBucket: 'engoapp-91373.firebasestorage.app',
    iosBundleId: 'com.example.enGoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfqGSko9gfFalkxltbzVipg7AXf3grs2c',
    appId: '1:601431274476:ios:9b792cb3b8cc9d883406c9',
    messagingSenderId: '601431274476',
    projectId: 'engoapp-91373',
    storageBucket: 'engoapp-91373.firebasestorage.app',
    iosBundleId: 'com.example.enGoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAps2sPcA7_Qvv5Z_l_KOWTuy79C8uiBiE',
    appId: '1:601431274476:web:c0ab32d5501d29393406c9',
    messagingSenderId: '601431274476',
    projectId: 'engoapp-91373',
    authDomain: 'engoapp-91373.firebaseapp.com',
    storageBucket: 'engoapp-91373.firebasestorage.app',
    measurementId: 'G-5JZGFX1D65',
  );
}
